version: 0.0
os: linux
files:
  - source: /sampleweb.war
    destination: /home/ec2-user/apache-tomcat-7.0.82/webapps
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
